name = "Aero"
author = "Fufius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff0cf001de93f0fda39dc278bd0dd58bf02cb755c86ec75737016075558cbffe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
