name = "Aero"
author = "Fufius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3a5cf954ee3274a5b50a5edbdb9011ad05aa2ff1dab06ee40ef76f15f95daae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
