name = "Aero"
author = "Fufius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fa0fab664eabfb296d2d91e0bfaec97a842784e78e9ff5684b7d59e978d501c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
